export const resList = [
  {
    Restaurant_Name: "Sample Restaurant 1",
    URL: "https://www.sample-restaurant1.com",
    Timing: "10:00 AM - 10:00 PM",
    Address: "123 Main Street, Sample City",
    Location: "Sample Location",
    City: "Sample City",
    Offer: "10% off on orders over $50",
    Contact_Number: "+1 123-456-7890",
    Cost_for_two: 40,
    Restaurant_Type: "Cuisine Type 1",
    Ratings_for_Swiggy: 4.5,
  },
  {
    Restaurant_Name: "Sample Restaurant 2",
    URL: "https://www.sample-restaurant2.com",
    Timing: "11:00 AM - 9:00 PM",
    Address: "456 Elm Street, Another City",
    Location: "Another Location",
    City: "Another City",
    Offer: "Free dessert with every meal",
    Contact_Number: "+1 987-654-3210",
    Cost_for_two: 30,
    Restaurant_Type: "Cuisine Type 2",
    Ratings_for_Swiggy: 4.0,
  },
];
